### ISSUE TITLE
Signo tabla seno

### ISSUE THREAD

**Issue by jlg-curso-dsi** [dsi-fceia/STM32F401-SenoGen#1]
Cambiar el signo en el penúltimo valor de
static const int16_t sine_1khz_FS8khz[SINE_GEN_1KHZ_LENGTH] =
{
  0, 23169, 32767, 23169, 0, -23169, 32767, -23169
};
en la linea 86 de application.c
Saludos

**Comment by pista86** [comment]
Solucionado
